import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Navbar from '@/components/navbar/Navbar';
import { ThemeProvider } from '@/components/theme-provider';

const pretendard = localFont({
  src: '../public/fonts/pretendard/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang='en' suppressHydrationWarning>
        <body className={`${pretendard.className} antialiased`}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <main className='container py-10'>{children}</main>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
